FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5170
EXPOSE 5171


FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["apiToDo/apiToDo.csproj", "apiToDo/"]
RUN dotnet restore "/src/apiToDo/apiToDo.csproj"
COPY . . 
WORKDIR "/src/apiToDo"
RUN dotnet build "./apiToDo.csproj" -c $BUILD_CONFIGURATION -o /app/build


FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./apiToDo.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "apiToDo.dll"]